# .github/workflows/daily_url_access.yml

name: Daily ROUSI Access

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: # 添加这一行，允许手动触发
jobs:
  access_url:
    runs-on: ubuntu-latest
    steps:
    - name: Install pup
      run: |
        PUP_VERSION="v0.4.0" # Specify the desired version
        curl -Lo pup.zip "https://github.com/ericchiang/pup/releases/download/${PUP_VERSION}/pup_${PUP_VERSION}_linux_amd64.zip"
        unzip pup.zip -d /usr/local/bin
        rm pup.zip
        pup --version
    - name: Access the URL
      run: |
        pup --version
        RESPONSE_FILE="response.html" 
        echo "Accessing and saving response ..."
        curl -s -o $RESPONSE_FILE 'https://rousi.zip/attendance.php' \
          -X 'GET' \
          -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' \
          -H 'Sec-Fetch-Site: same-origin' \
          -H 'Cookie: ${{ secrets.MY_ROUSI_SECRET }}' \
          -H 'Sec-Fetch-Dest: document' \
          -H 'Accept-Language: zh-CN,zh-Hans;q=0.9' \
          -H 'Sec-Fetch-Mode: navigate' \
          -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 Safari/605.1.15' \
          -H 'Accept-Encoding: gzip, deflate, br' \
          -H 'Referer: https://rousi.zip/' \
          -H 'Priority: u=0, i'
        echo "-------------"
        EXTRACTED_CONTENT=$(cat "$RESPONSE_FILE" | pup '#info_block > tbody > tr > td > table > tbody > tr > td:nth-child(1) > span > a:nth-child(7) text{}')
           
        echo "$EXTRACTED_CONTENT"
        
